//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortIt.Resources.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SortIt.Resources.Constants.ImageResources", typeof(ImageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_glass_bottle.svg.
        /// </summary>
        internal static string a_glass_bottle {
            get {
                return ResourceManager.GetString("a_glass_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_glass_jar.svg.
        /// </summary>
        internal static string a_glass_jar {
            get {
                return ResourceManager.GetString("a_glass_jar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_drop.svg.
        /// </summary>
        internal static string avatar_drop {
            get {
                return ResourceManager.GetString("avatar_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_earth.svg.
        /// </summary>
        internal static string avatar_earth {
            get {
                return ResourceManager.GetString("avatar_earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_leaf.svg.
        /// </summary>
        internal static string avatar_leaf {
            get {
                return ResourceManager.GetString("avatar_leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_panda.svg.
        /// </summary>
        internal static string avatar_panda {
            get {
                return ResourceManager.GetString("avatar_panda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b_battery.svg.
        /// </summary>
        internal static string b_battery {
            get {
                return ResourceManager.GetString("b_battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b_lightbulb.svg.
        /// </summary>
        internal static string b_lightbulb {
            get {
                return ResourceManager.GetString("b_lightbulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c_bottle_deposit.svg.
        /// </summary>
        internal static string c_bottle_deposit {
            get {
                return ResourceManager.GetString("c_bottle_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c_can_deposit.svg.
        /// </summary>
        internal static string c_can_deposit {
            get {
                return ResourceManager.GetString("c_can_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.svg.
        /// </summary>
        internal static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d_box.svg.
        /// </summary>
        internal static string d_box {
            get {
                return ResourceManager.GetString("d_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d_newspaper.svg.
        /// </summary>
        internal static string d_newspaper {
            get {
                return ResourceManager.GetString("d_newspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e_metal_can.svg.
        /// </summary>
        internal static string e_metal_can {
            get {
                return ResourceManager.GetString("e_metal_can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e_plastic_wrapper.svg.
        /// </summary>
        internal static string e_plastic_wrapper {
            get {
                return ResourceManager.GetString("e_plastic_wrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f_cup.svg.
        /// </summary>
        internal static string f_cup {
            get {
                return ResourceManager.GetString("f_cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f_plate.svg.
        /// </summary>
        internal static string f_plate {
            get {
                return ResourceManager.GetString("f_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag_en.svg.
        /// </summary>
        internal static string flag_en {
            get {
                return ResourceManager.GetString("flag_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag_et.svg.
        /// </summary>
        internal static string flag_et {
            get {
                return ResourceManager.GetString("flag_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag_ru.svg.
        /// </summary>
        internal static string flag_ru {
            get {
                return ResourceManager.GetString("flag_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g_mask.svg.
        /// </summary>
        internal static string g_mask {
            get {
                return ResourceManager.GetString("g_mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g_tissue.svg.
        /// </summary>
        internal static string g_tissue {
            get {
                return ResourceManager.GetString("g_tissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game.svg.
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_logo.svg.
        /// </summary>
        internal static string game_logo {
            get {
                return ResourceManager.GetString("game_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guide.svg.
        /// </summary>
        internal static string guide {
            get {
                return ResourceManager.GetString("guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h_apple_core.svg.
        /// </summary>
        internal static string h_apple_core {
            get {
                return ResourceManager.GetString("h_apple_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h_banana_peel.svg.
        /// </summary>
        internal static string h_banana_peel {
            get {
                return ResourceManager.GetString("h_banana_peel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idle_bin.svg.
        /// </summary>
        internal static string idle_bin {
            get {
                return ResourceManager.GetString("idle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moon.svg.
        /// </summary>
        internal static string moon {
            get {
                return ResourceManager.GetString("moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pencil.svg.
        /// </summary>
        internal static string pencil {
            get {
                return ResourceManager.GetString("pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant_rank0_seedling.svg.
        /// </summary>
        internal static string plant_rank0_seedling {
            get {
                return ResourceManager.GetString("plant_rank0_seedling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant_rank1_sapling.svg.
        /// </summary>
        internal static string plant_rank1_sapling {
            get {
                return ResourceManager.GetString("plant_rank1_sapling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant_rank2_bush.svg.
        /// </summary>
        internal static string plant_rank2_bush {
            get {
                return ResourceManager.GetString("plant_rank2_bush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant_rank3_tree.svg.
        /// </summary>
        internal static string plant_rank3_tree {
            get {
                return ResourceManager.GetString("plant_rank3_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant_rank4_forest.svg.
        /// </summary>
        internal static string plant_rank4_forest {
            get {
                return ResourceManager.GetString("plant_rank4_forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.svg.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sun.svg.
        /// </summary>
        internal static string sun {
            get {
                return ResourceManager.GetString("sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trash_question.svg.
        /// </summary>
        internal static string trash_question {
            get {
                return ResourceManager.GetString("trash_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.svg.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome_image.svg.
        /// </summary>
        internal static string welcome_image {
            get {
                return ResourceManager.GetString("welcome_image", resourceCulture);
            }
        }
    }
}
