//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortIt.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SortIt.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klaaspakend_en.svg.
        /// </summary>
        internal static string a_klaaspakend {
            get {
                return ResourceManager.GetString("a_klaaspakend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string AccuracyText {
            get {
                return ResourceManager.GetString("AccuracyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All months.
        /// </summary>
        internal static string AllMonthsText {
            get {
                return ResourceManager.GetString("AllMonthsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis in progress....
        /// </summary>
        internal static string AnalysisInProgress {
            get {
                return ResourceManager.GetString("AnalysisInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple core.
        /// </summary>
        internal static string AppleCore {
            get {
                return ResourceManager.GetString("AppleCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string AprilText {
            get {
                return ResourceManager.GetString("AprilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string AugustText {
            get {
                return ResourceManager.GetString("AugustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ohtlikudjaatmed_en.svg.
        /// </summary>
        internal static string b_ohtlikudjaatmed {
            get {
                return ResourceManager.GetString("b_ohtlikudjaatmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana peel.
        /// </summary>
        internal static string BananaPeel {
            get {
                return ResourceManager.GetString("BananaPeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string BioText {
            get {
                return ResourceManager.GetString("BioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio waste container.
        /// </summary>
        internal static string BioWasteContainer {
            get {
                return ResourceManager.GetString("BioWasteContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardboard box.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Btn_Details {
            get {
                return ResourceManager.GetString("Btn_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light bulb.
        /// </summary>
        internal static string Bulb {
            get {
                return ResourceManager.GetString("Bulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pandipakend_en.svg.
        /// </summary>
        internal static string c_pandipakend {
            get {
                return ResourceManager.GetString("c_pandipakend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is not available.
        /// </summary>
        internal static string CameraNotAvailable {
            get {
                return ResourceManager.GetString("CameraNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device cannot take photos.
        /// </summary>
        internal static string CameraNotSupportedOnDevice {
            get {
                return ResourceManager.GetString("CameraNotSupportedOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission was not granted.
        /// </summary>
        internal static string CameraPermissionDenied {
            get {
                return ResourceManager.GetString("CameraPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission is required to take a photo.
        /// </summary>
        internal static string CameraPermissionRequired {
            get {
                return ResourceManager.GetString("CameraPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceramic shard.
        /// </summary>
        internal static string CeramicShard {
            get {
                return ResourceManager.GetString("CeramicShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereal box.
        /// </summary>
        internal static string CerealBox {
            get {
                return ResourceManager.GetString("CerealBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cigarette butt.
        /// </summary>
        internal static string CigaretteButt {
            get {
                return ResourceManager.GetString("CigaretteButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes and shoes container.
        /// </summary>
        internal static string ClothesShoesContainer {
            get {
                return ResourceManager.GetString("ClothesShoesContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct / Wrong.
        /// </summary>
        internal static string CorrectWrong {
            get {
                return ResourceManager.GetString("CorrectWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pappjapaberpakend_en.svg.
        /// </summary>
        internal static string d_pappjapaberpakend {
            get {
                return ResourceManager.GetString("d_pappjapaberpakend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string DecemberText {
            get {
                return ResourceManager.GetString("DecemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle with a deposit mark.
        /// </summary>
        internal static string DepositBootle {
            get {
                return ResourceManager.GetString("DepositBootle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can with a deposit mark.
        /// </summary>
        internal static string DepositCan {
            get {
                return ResourceManager.GetString("DepositCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit glass bottle.
        /// </summary>
        internal static string DepositGlass {
            get {
                return ResourceManager.GetString("DepositGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit packaging container.
        /// </summary>
        internal static string DepositPackagingContainer {
            get {
                return ResourceManager.GetString("DepositPackagingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string DepositText {
            get {
                return ResourceManager.GetString("DepositText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect.
        /// </summary>
        internal static string Detect {
            get {
                return ResourceManager.GetString("Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection failed.
        /// </summary>
        internal static string DetectionFailed {
            get {
                return ResourceManager.GetString("DetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection succeeded.
        /// </summary>
        internal static string DetectionSucceeded {
            get {
                return ResourceManager.GetString("DetectionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect waste.
        /// </summary>
        internal static string DetectWaste {
            get {
                return ResourceManager.GetString("DetectWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plastmetalljoogikartong_en.svg.
        /// </summary>
        internal static string e_plastmetalljoogikartong {
            get {
                return ResourceManager.GetString("e_plastmetalljoogikartong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg shells.
        /// </summary>
        internal static string EggShells {
            get {
                return ResourceManager.GetString("EggShells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics container.
        /// </summary>
        internal static string ElectronicsContainer {
            get {
                return ResourceManager.GetString("ElectronicsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope.
        /// </summary>
        internal static string Envelope {
            get {
                return ResourceManager.GetString("Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit_Button {
            get {
                return ResourceManager.GetString("Exit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ringlusnoud_en.svg.
        /// </summary>
        internal static string f_ringlusnoud {
            get {
                return ResourceManager.GetString("f_ringlusnoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string FebruaryText {
            get {
                return ResourceManager.GetString("FebruaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film/wrapping.
        /// </summary>
        internal static string FilmWrapping {
            get {
                return ResourceManager.GetString("FilmWrapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segaolmejaatmed_en.svg.
        /// </summary>
        internal static string g_segaolmejaatmed {
            get {
                return ResourceManager.GetString("g_segaolmejaatmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test your recycling knowledge ♻️.
        /// </summary>
        internal static string Game_Challenge_Message {
            get {
                return ResourceManager.GetString("Game_Challenge_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco Challenge.
        /// </summary>
        internal static string Game_Challenge_Title {
            get {
                return ResourceManager.GetString("Game_Challenge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Game_Title {
            get {
                return ResourceManager.GetString("Game_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass bottle.
        /// </summary>
        internal static string GlassBootle {
            get {
                return ResourceManager.GetString("GlassBootle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass jar.
        /// </summary>
        internal static string GlassCan {
            get {
                return ResourceManager.GetString("GlassCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass jar lid.
        /// </summary>
        internal static string GlassJarLid {
            get {
                return ResourceManager.GetString("GlassJarLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass packaging container.
        /// </summary>
        internal static string GlassPackagingContainer {
            get {
                return ResourceManager.GetString("GlassPackagingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        internal static string GlassText {
            get {
                return ResourceManager.GetString("GlassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Greeting_Text {
            get {
                return ResourceManager.GetString("Greeting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide_Title {
            get {
                return ResourceManager.GetString("Guide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to biojaatmed_en.svg.
        /// </summary>
        internal static string h_biojaatmed {
            get {
                return ResourceManager.GetString("h_biojaatmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vanapaber_en.svg.
        /// </summary>
        internal static string h_vanapaber {
            get {
                return ResourceManager.GetString("h_vanapaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        internal static string HazardousText {
            get {
                return ResourceManager.GetString("HazardousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous waste container.
        /// </summary>
        internal static string HazardousWasteContainer {
            get {
                return ResourceManager.GetString("HazardousWasteContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image is required to start analysis.
        /// </summary>
        internal static string ImageRequiredForAnalysis {
            get {
                return ResourceManager.GetString("ImageRequiredForAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image selected.
        /// </summary>
        internal static string ImageSelected_ResultText {
            get {
                return ResourceManager.GetString("ImageSelected_ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo added. Tap &quot;Detect waste&quot;.
        /// </summary>
        internal static string ImageSelected_StatusText {
            get {
                return ResourceManager.GetString("ImageSelected_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string JanuaryText {
            get {
                return ResourceManager.GetString("JanuaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juice carton.
        /// </summary>
        internal static string JuiceCarton {
            get {
                return ResourceManager.GetString("JuiceCarton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string JulyText {
            get {
                return ResourceManager.GetString("JulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string JuneText {
            get {
                return ResourceManager.GetString("JuneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose avatar.
        /// </summary>
        internal static string Label_ChooseAvatar {
            get {
                return ResourceManager.GetString("Label_ChooseAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecology Level.
        /// </summary>
        internal static string Label_EcoLevel {
            get {
                return ResourceManager.GetString("Label_EcoLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Label_Lvl {
            get {
                return ResourceManager.GetString("Label_Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name.
        /// </summary>
        internal static string Label_PlayerName {
            get {
                return ResourceManager.GetString("Label_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Label_Statistics {
            get {
                return ResourceManager.GetString("Label_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco Scout 🐾.
        /// </summary>
        internal static string LabelRank_EcoScout {
            get {
                return ResourceManager.GetString("LabelRank_EcoScout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Hero 💚.
        /// </summary>
        internal static string LabelRank_GreenHero {
            get {
                return ResourceManager.GetString("LabelRank_GreenHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Guardian 🌍.
        /// </summary>
        internal static string LabelRank_PlanetGuardian {
            get {
                return ResourceManager.GetString("LabelRank_PlanetGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycler ♻️.
        /// </summary>
        internal static string LabelRank_Recycler {
            get {
                return ResourceManager.GetString("LabelRank_Recycler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seedling 🌱.
        /// </summary>
        internal static string LabelRank_Seedling {
            get {
                return ResourceManager.GetString("LabelRank_Seedling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string LabelStats_Correct {
            get {
                return ResourceManager.GetString("LabelStats_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        internal static string LabelStats_Wrong {
            get {
                return ResourceManager.GetString("LabelStats_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level up! 🎉.
        /// </summary>
        internal static string LvlUp {
            get {
                return ResourceManager.GetString("LvlUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine.
        /// </summary>
        internal static string Magazine {
            get {
                return ResourceManager.GetString("Magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string MarchText {
            get {
                return ResourceManager.GetString("MarchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string MayText {
            get {
                return ResourceManager.GetString("MayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical mask.
        /// </summary>
        internal static string MedicalMask {
            get {
                return ResourceManager.GetString("MedicalMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal can.
        /// </summary>
        internal static string MetalCan {
            get {
                return ResourceManager.GetString("MetalCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        internal static string MixedText {
            get {
                return ResourceManager.GetString("MixedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed municipal waste container.
        /// </summary>
        internal static string MixedWasteContainer {
            get {
                return ResourceManager.GetString("MixedWasteContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napkin.
        /// </summary>
        internal static string Napkin {
            get {
                return ResourceManager.GetString("Napkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newspaper.
        /// </summary>
        internal static string Newspaper {
            get {
                return ResourceManager.GetString("Newspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📷 No image.
        /// </summary>
        internal static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook.
        /// </summary>
        internal static string Notebook {
            get {
                return ResourceManager.GetString("Notebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not waste.
        /// </summary>
        internal static string NotWaste {
            get {
                return ResourceManager.GetString("NotWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string NovemberText {
            get {
                return ResourceManager.GetString("NovemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not detected.
        /// </summary>
        internal static string ObjectNotDetected {
            get {
                return ResourceManager.GetString("ObjectNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string OctoberText {
            get {
                return ResourceManager.GetString("OctoberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old book.
        /// </summary>
        internal static string OldBook {
            get {
                return ResourceManager.GetString("OldBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint can.
        /// </summary>
        internal static string PaintCan {
            get {
                return ResourceManager.GetString("PaintCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper bag.
        /// </summary>
        internal static string PaperBag {
            get {
                return ResourceManager.GetString("PaperBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper and cardboard container.
        /// </summary>
        internal static string PaperCardboardContainer {
            get {
                return ResourceManager.GetString("PaperCardboardContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper/newspaper.
        /// </summary>
        internal static string PaperNewspaper {
            get {
                return ResourceManager.GetString("PaperNewspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string PaperPackagingText {
            get {
                return ResourceManager.GetString("PaperPackagingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfume bottle.
        /// </summary>
        internal static string PerfumeBottle {
            get {
                return ResourceManager.GetString("PerfumeBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo capture was cancelled.
        /// </summary>
        internal static string PhotoCaptureCancelled {
            get {
                return ResourceManager.GetString("PhotoCaptureCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic bottle.
        /// </summary>
        internal static string PlasticBottle {
            get {
                return ResourceManager.GetString("PlasticBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic bottle cap.
        /// </summary>
        internal static string PlasticBottleCap {
            get {
                return ResourceManager.GetString("PlasticBottleCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic and metal packaging container.
        /// </summary>
        internal static string PlasticMetalContainer {
            get {
                return ResourceManager.GetString("PlasticMetalContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plast./met..
        /// </summary>
        internal static string PMB_CartonText {
            get {
                return ResourceManager.GetString("PMB_CartonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress by days.
        /// </summary>
        internal static string ProgressDaysTitle {
            get {
                return ResourceManager.GetString("ProgressDaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress by months.
        /// </summary>
        internal static string ProgressMonthsTitle {
            get {
                return ResourceManager.GetString("ProgressMonthsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset profile.
        /// </summary>
        internal static string Reset_Button {
            get {
                return ResourceManager.GetString("Reset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusable bottle.
        /// </summary>
        internal static string ReusableBottle {
            get {
                return ResourceManager.GetString("ReusableBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusable cutlery.
        /// </summary>
        internal static string ReusableCutlery {
            get {
                return ResourceManager.GetString("ReusableCutlery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusable mug.
        /// </summary>
        internal static string ReusableMug {
            get {
                return ResourceManager.GetString("ReusableMug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusable plate.
        /// </summary>
        internal static string ReusablePlate {
            get {
                return ResourceManager.GetString("ReusablePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse.
        /// </summary>
        internal static string ReusableText {
            get {
                return ResourceManager.GetString("ReusableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round completed.
        /// </summary>
        internal static string RoundOver {
            get {
                return ResourceManager.GetString("RoundOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        internal static string ScrapPaperText {
            get {
                return ResourceManager.GetString("ScrapPaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select year.
        /// </summary>
        internal static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string SeptemberText {
            get {
                return ResourceManager.GetString("SeptemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose theme.
        /// </summary>
        internal static string Settings_ChooseTheme {
            get {
                return ResourceManager.GetString("Settings_ChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sound.
        /// </summary>
        internal static string Settings_EnableSound {
            get {
                return ResourceManager.GetString("Settings_EnableSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo to find the correct container 🌿.
        /// </summary>
        internal static string TakePhoto_Message {
            get {
                return ResourceManager.GetString("TakePhoto_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo for detection.
        /// </summary>
        internal static string TakePhotoAnalysis {
            get {
                return ResourceManager.GetString("TakePhotoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo first.
        /// </summary>
        internal static string TakePhotoFirst {
            get {
                return ResourceManager.GetString("TakePhotoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string TapStartHint {
            get {
                return ResourceManager.GetString("TapStartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tea bag.
        /// </summary>
        internal static string TeaBag {
            get {
                return ResourceManager.GetString("TeaBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Level Up.
        /// </summary>
        internal static string TestLevelUpButton {
            get {
                return ResourceManager.GetString("TestLevelUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury thermometer.
        /// </summary>
        internal static string Thermometer {
            get {
                return ResourceManager.GetString("Thermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal lid.
        /// </summary>
        internal static string TinLid {
            get {
                return ResourceManager.GetString("TinLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toothbrush.
        /// </summary>
        internal static string Toothbrush {
            get {
                return ResourceManager.GetString("Toothbrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total answers.
        /// </summary>
        internal static string TotalAnswersText {
            get {
                return ResourceManager.GetString("TotalAnswersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable peels.
        /// </summary>
        internal static string VegetablePeels {
            get {
                return ResourceManager.GetString("VegetablePeels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste type statistics.
        /// </summary>
        internal static string WasteTypeStatistics {
            get {
                return ResourceManager.GetString("WasteTypeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app helps you learn waste sorting.
        ///Play, choose the right bins, and earn points..
        /// </summary>
        internal static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Welcome_Start {
            get {
                return ResourceManager.GetString("Welcome_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SortIt!.
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP earned.
        /// </summary>
        internal static string XPGet {
            get {
                return ResourceManager.GetString("XPGet", resourceCulture);
            }
        }
    }
}
